name: NASA Project CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    env:
      CI: true
      MONGO_URL: mongodb://localhost/nasa
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14.x, 16.x]
        mongodb-version: ['4.4']

    steps:
      - name: Git checkout
        uses: actions/checkout@v2

      - name: Use Node.js version ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}

      - name: Use MongoDB in GitHub Actions
        uses: supercharge/mongodb-github-action@1.8.0
        with:
          mongodb-version: ${{ matrix.mongodb-version }}      
      
      - run: npm install
      - run: npm run build --prefix client
      - run: npm test